---
title: "West Nile Virus Prediction EDA"
author: "Oscar Cassetti"
date: "November 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.height=9, fig.width=12)
```

# Maps

```{r}
library(ggmap) 
library(dplyr)
library(ggplot2)

dataDir <- "../input"
wnv <- read.csv(file.path(dataDir, "train.csv"))
test <- read.csv(file.path(dataDir, "test.csv"))
spray <- read.csv(file.path(dataDir, "spray.csv"))

weather <- read.csv(file.path(dataDir, "weather.csv"), stringsAsFactors = FALSE)

mapdata <- readRDS(file.path(dataDir, "mapdata_copyright_openstreetmap_contributors.rds"))

latlong <- c("Longitude", "Latitude")

#weatherStation <- matrix(c( -87.933 , 41.995, -87.752, 41.786), ncol = 2, byrow = TRUE)
weatherStation <- matrix(c( -87.933 , 41.995), ncol = 2, byrow = TRUE)

```

```{r}

hhMMToSeconds <- function(x){
  x <- as.numeric(x)/100
  floor(x) * 3600 + (x - floor(x) ) * 60
}

weather <- weather %>% filter(Station==1) %>% arrange(Date) 

weather <- weather %>% mutate(Tavg=if_else(Tavg == "M" , as.character(Tmax - Tmin), as.character(Tavg)))

weather <- weather %>% arrange(Date, Station) %>% mutate(Depart=as.numeric(if_else(Depart=="M", lag(Depart), Depart)))
weather <- weather %>% arrange(Date, Station) %>% mutate(Sunrise=if_else(Sunrise=="-", as.character(lag(Sunrise)), as.character(Sunrise)))
weather <- weather %>% arrange(Date, Station) %>% mutate(Sunset=if_else(Sunset=="-", as.character(lag(Sunset)), as.character(Sunset)))


weather <- weather %>% mutate(Sunrise=hhMMToSeconds(Sunrise), Sunset=hhMMToSeconds(Sunset)) %>% mutate(DayLenght=(Sunset-Sunrise)) #%>%
#mutate(DayLenght=(DayLenght - min(DayLenght))/(max(DayLenght) - min(DayLenght)))

weather <- weather[, -which(colnames(weather) %in% c("Depth", "Water1", "SnowFall", "CodeSum"))]
weather$Date <- as.Date(weather$Date, format="%Y-%m-%d")

#weather$CodeSum <- factor(weather$CodeSum)

for(i in 1:ncol(weather)){
 if(class(weather[, i]) == "character"){
   xVal <- trimws(weather[, i])
   xValMin <- min(as.numeric(xVal), na.rm = TRUE)
   xVal <- replace(xVal,  xVal == 'T', xValMin)
   xVal <- replace(xVal,  xVal == 'M', mean(as.numeric(xVal), na.rm = TRUE))
   xVal <- as.numeric(xVal) #- min(xVal, na.rm = TRUE)) / (max(xVal, na.rm = TRUE) - min(xVal, na.rm = TRUE))
   weather[, i] <- 
     if_else(is.na(xVal), -1, xVal)
 }
}

weatherLagged <- union_all(
filter(weather, Station==1) %>% arrange(Station, Date) %>% mutate(WetBulb1=lag(WetBulb, order_by=Date), 
                                                                  WetBulb3=lag(WetBulb, n = 3, order_by=Date),
                                                                  WetBulb5=lag(WetBulb, n = 5, order_by=Date),
                                                                  WetBulb8=lag(WetBulb, n = 8, order_by=Date),
                                                                  WetBulb12=lag(WetBulb, n = 12, order_by=Date),
                                                                  DewPoint1=lag(DewPoint, order_by=Date), 
                                                                  DewPoint3=lag(DewPoint, n = 3, order_by=Date),
                                                                  DewPoint5=lag(DewPoint, n = 5, order_by=Date),
                                                                  DewPoint8=lag(DewPoint, n = 8, order_by=Date),
                                                                  DewPoint12=lag(DewPoint, n = 12, order_by=Date),
                                                                  PrecipTotal1=lag(PrecipTotal, order_by=Date),
                                                                  PrecipTotal3=lag(PrecipTotal, n = 3, order_by=Date),
                                                                  PrecipTotal5=lag(PrecipTotal, n = 5, order_by=Date),
                                                                  PrecipTotal8=lag(PrecipTotal, n = 8, order_by=Date),
                                                                  PrecipTotal12=lag(PrecipTotal, n = 12, order_by=Date),
                                                                  Tavg1=lag(Tavg, order_by=Date),
                                                                  Tavg3=lag(Tavg, n = 3, order_by=Date),
                                                                  Tavg5=lag(Tavg, n = 5, order_by=Date),
                                                                  Tavg8=lag(Tavg, n = 8, order_by=Date),
                                                                  Tavg12=lag(Tavg, n = 12, order_by=Date),
                                                                  Tmax1=lag(Tmax, order_by=Date),
                                                                  Tmax3=lag(Tmax, n = 3, order_by=Date),
                                                                  Tmax5=lag(Tmax, n = 5, order_by=Date),
                                                                  Tmax8=lag(Tmax, n = 8, order_by=Date),
                                                                  Tmax12=lag(Tmax, n = 12, order_by=Date),
                                                                  Tmin1=lag(Tmin, order_by=Date),
                                                                  Tmin3=lag(Tmin, n = 3, order_by=Date),
                                                                  Tmin5=lag(Tmin, n = 5, order_by=Date),
                                                                  Tmin8=lag(Tmin, n = 8, order_by=Date),
                                                                  Tmin12=lag(Tmin, n = 12, order_by=Date)                                                 
                                                                  ) ,
filter(weather, Station==2) %>% arrange(Station, Date) %>% mutate(WetBulb1=lag(WetBulb, order_by=Date), 
                                                                  WetBulb3=lag(WetBulb, n = 3, order_by=Date),
                                                                  WetBulb5=lag(WetBulb, n = 5, order_by=Date),
                                                                  WetBulb8=lag(WetBulb, n = 8, order_by=Date),
                                                                  WetBulb12=lag(WetBulb, n = 12, order_by=Date),
                                                                  DewPoint1=lag(DewPoint, order_by=Date), 
                                                                  DewPoint3=lag(DewPoint, n = 3, order_by=Date),
                                                                  DewPoint5=lag(DewPoint, n = 5, order_by=Date),
                                                                  DewPoint8=lag(DewPoint, n = 8, order_by=Date),
                                                                  DewPoint12=lag(DewPoint, n = 12, order_by=Date),
                                                                  PrecipTotal1=lag(PrecipTotal, order_by=Date),
                                                                  PrecipTotal3=lag(PrecipTotal, n = 3, order_by=Date),
                                                                  PrecipTotal5=lag(PrecipTotal, n = 5, order_by=Date),
                                                                  PrecipTotal8=lag(PrecipTotal, n = 8, order_by=Date),
                                                                  PrecipTotal12=lag(PrecipTotal, n = 12, order_by=Date),
                                                                  Tavg1=lag(Tavg, order_by=Date),
                                                                  Tavg3=lag(Tavg, n = 3, order_by=Date),
                                                                  Tavg5=lag(Tavg, n = 5, order_by=Date),
                                                                  Tavg8=lag(Tavg, n = 8, order_by=Date),
                                                                  Tavg12=lag(Tavg, n = 12, order_by=Date),
                                                                  Tmax1=lag(Tmax, order_by=Date),
                                                                  Tmax3=lag(Tmax, n = 3, order_by=Date),
                                                                  Tmax5=lag(Tmax, n = 5, order_by=Date),
                                                                  Tmax8=lag(Tmax, n = 8, order_by=Date),
                                                                  Tmax12=lag(Tmax, n = 12, order_by=Date),
                                                                  Tmin1=lag(Tmin, order_by=Date),
                                                                  Tmin3=lag(Tmin, n = 3, order_by=Date),
                                                                  Tmin5=lag(Tmin, n = 5, order_by=Date),
                                                                  Tmin8=lag(Tmin, n = 8, order_by=Date),
                                                                  Tmin12=lag(Tmin, n = 12, order_by=Date)  
                                                                  )  
) %>% arrange(Date, Station)

startColIdx <- ncol(weather) + 1

for( i in seq(startColIdx, ncol(weatherLagged))){
  xVal <- weatherLagged[,i]
  weatherLagged[, i] <- if_else(is.na(xVal), mean(xVal, na.rm = TRUE), as.numeric(xVal))
}

library(zoo)

for (colName in colnames(weatherLagged)[3:18]){
    movingAvgName <- sprintf("%sMA",colName)
    weatherLagged[, movingAvgName] <- rollmean(weatherLagged[, colName], 10, align = "right", fill = mean(weatherLagged[1:10, colName]))
 }

weatherLagged

weather <- weatherLagged 

```

```{r}
ggmap(mapdata) + 
  geom_point(aes(x=Longitude, y=Latitude, color="spray"), data=spray) +
  geom_point(aes(x=Longitude, y=Latitude, color="traps"), data=wnv) +
  #geom_point(aes(x=Longitude, y=Latitude, color="virus"), data=wnv[wnv$WnvPresent == 1, ]) +
  ggtitle("Mosquito Traps and Spray Locations")

```
```{r}

wnvAgg <- wnv %>% select(Date, Address, Species, Block, Street, Trap, Latitude, Longitude, AddressAccuracy, NumMosquitos, WnvPresent) %>%
  group_by(Date, Address, Species, Block, Street, Trap, Latitude, Longitude, AddressAccuracy) %>%
  summarise(NumMosquitos=sum(NumMosquitos), WnvPresent=max(WnvPresent), Tcount=length(Trap))

range(wnvAgg$Tcount)

wnvAgg$Date <- as.Date(wnvAgg$Date, format="%Y-%m-%d")
wnvAgg$WnvPresent <- factor(wnvAgg$WnvPresent)


wnvAgg[, c("Year", "Month", "Week", "Day")] <- cbind(as.numeric(strftime(wnvAgg$Date, "%Y")), as.numeric(strftime(wnvAgg$Date, "%m")), 
                                                    as.numeric(strftime(wnvAgg$Date, "%U")), as.numeric(strftime(wnvAgg$Date, "%d")))

ggplot(wnvAgg, aes(x=Week, y=NumMosquitos)) + geom_bar(aes(fill=WnvPresent), stat = "identity") + facet_wrap(~Year, scales = "free_x") 

```


```{r}

spray$Date <- as.Date(spray$Date)
spray[, c("Year", "Month", "Week", "Day")] <- cbind(as.numeric(strftime(spray$Date, "%Y")), as.numeric(strftime(spray$Date, "%m")), 
                                                    as.numeric(strftime(spray$Date, "%U")), as.numeric(strftime(spray$Date, "%d")))   

ggmap(mapdata) +
  geom_point(aes(x=Longitude, y=Latitude, color="traps"), data=wnvAgg, alpha=0.8) +
  geom_point(aes(x=Longitude, y=Latitude, color="virus"), data=wnvAgg[wnvAgg$WnvPresent == 1 ,], alpha=0.5) +
   geom_point(aes(x=Longitude, y=Latitude, color="spray"), data=spray, alpha=0.5) +
    facet_wrap(~Year+Month) +
  #geom_point(aes(x=Longitude, y=Latitude, color="virus"), data=wnv[wnv$WnvPresent == 1, ]) +
  ggtitle("Mosquito Traps and Spray Locations")


## TODO compute conditional on month and year and write time series
```
```{r}
library(geosphere)

udateDf <- expand.grid(wnwDate = unique(wnvAgg$Date), sprayDate = unique(spray$Date))

udateDf <- udateDf %>% mutate(delta=wnwDate - sprayDate) %>% filter(delta > 0 & delta < 8) %>% group_by(wnwDate) %>% 
  summarise(sprayDate=min(sprayDate), delta=min(delta))


trsp <- wnvAgg %>% inner_join(udateDf, by = c("Date" = "wnwDate"))
  
mtrsp <- as.matrix(trsp[, c("Longitude", "Latitude")], ncol=2)

spr <- unique(spray[spray$Date %in% udateDf$sprayDate, latlong])

mspr <- as.matrix(spr, ncol=2) 

# distances in meter
mdist <- distm(mtrsp, mspr)

mdist <- unique(which(mdist < 1000, arr.ind=TRUE)[,1] )

trsp <- trsp[mdist,]


trsp2 <- wnvAgg %>% inner_join(unique(trsp[, c(latlong)]), by=c("Latitude", "Longitude")) %>% 
  left_join(unique(trsp[, c(latlong, "Date", "sprayDate", "Week")]), by=c("Latitude" = "Latitude", "Longitude" = "Latitude", "Date" = "Date"))


trsp2$Sprayed <-  factor(if_else(!is.na(trsp2$sprayDate), 1, 0))

ggplot(trsp2[trsp2$Year %in% c(2011, 2013), ]) + geom_line(aes(x=Week.x, y=NumMosquitos)) +
  geom_point(aes(x=Week.x , y=NumMosquitos, color="spray"), data=trsp2[trsp2$Sprayed ==1, ]) +
  facet_wrap(~Year+Trap, scales = "free") 



```
```{r}

chRateDf <- wnvAgg %>% group_by(Trap, Species, Date ) %>% arrange(Trap, Species, Date) %>% summarise(NumMosquitos=sum(NumMosquitos))  %>% mutate(chRate=
                                             ( NumMosquitos - lag(NumMosquitos, default = NA)) /
                                             as.double( Date - lag(Date, default = NA) )
                                             ) %>% arrange(Trap, Species, Date)

wnvAgg <- wnvAgg %>% left_join(chRateDf, by=c("Date", "Trap", "Species"), suffix=c("", "_Y")) %>% select(c(colnames(wnvAgg),"chRate")) 


```

```{r}
uLocations <- unique(wnvAgg[, latlong])

weatherMatrixDistance <- distm(uLocations,weatherStation )

uLocations$closestStation <- apply(weatherMatrixDistance, 1, function(x){
  minDist<-min(x)
  #which(x == m)
  # return distance 
  minDist})



#wnvAgg <- wnvAgg %>% left_join(uLocations)  %>% left_join(weather, by=c("closestStation" =  "Station", "Date" = "Date"))
wnvAgg <- wnvAgg %>% left_join(uLocations, by=c("Latitude", "Longitude"))  %>% left_join(weather, by=c("Date" = "Date"))

```

Hard to undestand if we can label all mosquitos in the trap as with the virus
```{r}

speciesSummary <- wnvAgg %>%  group_by(Week, Year, Species, WnvPresent) %>% summarise(LogSumNumMosquitos=log(sum(NumMosquitos)))
speciesSummary
ggplot(speciesSummary) + geom_bar(aes(x=Week, y=LogSumNumMosquitos, fill=WnvPresent), stat = "identity") + facet_wrap(~Species+Year)

speciesSummary <- wnvAgg %>% group_by(Species, WnvPresent) %>% summarise(Count=length(NumMosquitos))

ggplot(speciesSummary) + geom_bar(aes(x=Species, y=Count, fill=WnvPresent), stat = "identity")

targetSpecies <- speciesSummary %>% filter(WnvPresent==1)

species <- as.character(wnvAgg$Species)
table(species)

wnvAgg$Species <- factor(if_else(species %in% c("CULEX PIPIENS", "CULEX PIPIENS/RESTUANS", "CULEX RESTUANS"), species, "other"))

speciesSummary <- wnvAgg %>%  group_by(Week, Year, Species, WnvPresent) %>% summarise(LogSumNumMosquitos=log(sum(NumMosquitos)))
speciesSummary
ggplot(speciesSummary) + geom_bar(aes(x=Week, y=LogSumNumMosquitos, fill=WnvPresent), stat = "identity") + facet_wrap(~Species+Year)

speciesSummary <- wnvAgg %>% group_by(Species, WnvPresent) %>% summarise(Count=length(NumMosquitos))

ggplot(speciesSummary) + geom_bar(aes(x=Species, y=Count, fill=WnvPresent), stat = "identity")

wnvbySpecies <- wnvAgg %>% group_by(Species, Week) %>% summarise(pSpecies=sum(if_else(WnvPresent==1, 1, 0)/length(WnvPresent)))

wnvAgg<-wnvAgg %>% left_join(wnvbySpecies, by=c("Species", "Week"))
```
Virus does not occur in other species but needs checking

```{r}
setdiff(test$Trap, wnv$Trap)

wnvAgg$SatelliteTrap <- factor(if_else(nchar(substr(as.character(wnvAgg$Trap), 5,6)) > 0, 1, 0))

satelliteTrapSummary <- wnvAgg %>%  group_by(Month, Year, SatelliteTrap, WnvPresent) %>% summarise(NumMosquitos=sum(NumMosquitos))

ggplot(satelliteTrapSummary) + geom_bar(aes(x=Month, y=log(NumMosquitos), fill=WnvPresent), stat = "identity") + facet_wrap(~SatelliteTrap+Year)
```
Not clear the use of satellite traps


Hotspot distance rather than knn

```{r}

hotspotDf <- wnvAgg %>% group_by(Year, Latitude, Longitude) %>% summarise(p=sum(if_else(WnvPresent == 1, 1, 0))/length(WnvPresent))
hotspotDf <- hotspotDf %>% left_join(hotspotDf %>% group_by(Year) %>% summarise(p90=quantile(p, 0.90)), by="Year")


 ggmap(mapdata) + 
   geom_point(aes(x=Longitude, y=Latitude, color="virus"), data=subset(hotspotDf, p>=p90), alpha=0.9) +
#    geom_point(aes(x=Longitude, y=Latitude, color="spray"), data=spray, alpha=0.5) +
     facet_grid(~Year) +
#   #geom_point(aes(x=Longitude, y=Latitude, color="virus"), data=wnv[wnv$WnvPresent == 1, ]) +
   ggtitle("Potential hotspots")


hotspotDf <- subset(hotspotDf, p>=p90)


hotspotDf


distanceToHostpost <- as.data.frame(do.call(rbind,
lapply(unique(wnvAgg$Year), function(year){

hotSpotLocations <- as.matrix(hotspotDf[hotspotDf$Year == year, latlong], ncol=2)
trapLocation <- as.matrix(unique(wnvAgg[wnvAgg$Year == year, latlong]), ncol=2) 

trapToHostSpot <- distm(trapLocation, hotSpotLocations)

minToHotSpot <- apply(trapToHostSpot, 1, min)
maxToHotSpot <- apply(trapToHostSpot, 1, max)
avgToHotSpot <- apply(trapToHostSpot, 1, mean)

cbind(trapLocation, minToHotSpot, maxToHotSpot, avgToHotSpot, Year=rep(year, length(avgToHotSpot)))
})
))

wnvAgg <- wnvAgg %>% left_join(distanceToHostpost,  by = c("Latitude", "Longitude", "Year"))
```



```{r}
augmentTestData <- function(df, weatherStation = matrix(c( -87.933 , 41.995, -87.752, 41.786), ncol = 2, byrow = TRUE)){
  
  latlong <- c("Longitude", "Latitude")
 
  
  df$SatelliteTrap <- factor(if_else(nchar(substr(as.character(df$Trap), 5,6)) > 0, 1, 0))
 
  dfAgg <- df %>% select(Date, Species, SatelliteTrap, Trap, Block, Latitude, Longitude, AddressAccuracy,) %>%
  group_by(Date, Species, SatelliteTrap, Block, Trap, Latitude, Longitude, AddressAccuracy) %>% summarise(Tcount=length(SatelliteTrap))
 
  dfAgg <- left_join(df, dfAgg) %>% select(Date, Species, SatelliteTrap, Block, Latitude, Longitude, AddressAccuracy,Tcount)

dfAgg$Date <- as.Date(dfAgg$Date)
species <- as.character(dfAgg$Species)
dfAgg$Species <- factor(if_else(species %in% c("CULEX PIPIENS", "CULEX PIPIENS/RESTUANS", "CULEX RESTUANS"), species, "other"))


dfAgg[, c("Year", "Month", "Week", "Day")] <- cbind(as.numeric(strftime(dfAgg$Date, "%Y")), as.numeric(strftime(dfAgg$Date, "%m")), 
                                                    as.numeric(strftime(dfAgg$Date, "%U")), as.numeric(strftime(dfAgg$Date, "%d")))   


uLocations <- unique(dfAgg[, latlong])

weatherMatrixDistance <- distm(uLocations,weatherStation )

# uLocations$closestStation <- apply(weatherMatrixDistance, 1, function(x){
#   m<-min(x)
#   which(x == m)})
uLocations$closestStation <- apply(weatherMatrixDistance, 1, function(x){
  minDist<-min(x)
  minDist})




weather$Date <- as.Date(weather$Date, format="%Y-%m-%d")

#dfAgg <- dfAgg %>% left_join(uLocations)  %>% left_join(weather, by=c("closestStation" =  "Station", "Date" = "Date"))
dfAgg <- dfAgg %>% left_join(uLocations, by=c("Latitude", "Longitude"))  %>% left_join(weather, by=c("Date" = "Date"))

dfAgg <-  dfAgg %>% left_join(wnvbySpecies, by=c("Species", "Week"))

distanceToHostpost <- as.data.frame(do.call(rbind,
lapply(unique(dfAgg$Year), function(year){

hotSpotLocations <- as.matrix(hotspotDf[hotspotDf$Year == (year-1), latlong], ncol=2)
trapLocation <- as.matrix(unique(dfAgg[dfAgg$Year == year, latlong]), ncol=2) 

trapToHostSpot <- distm(trapLocation, hotSpotLocations)

minToHotSpot <- apply(trapToHostSpot, 1, min)
maxToHotSpot <- apply(trapToHostSpot, 1, max)
avgToHotSpot <- apply(trapToHostSpot, 1, mean)

cbind(trapLocation, minToHotSpot, maxToHotSpot, avgToHotSpot, Year=rep(year, length(avgToHotSpot)))
})
))

dfAgg <- dfAgg %>% left_join(distanceToHostpost,  by = c("Latitude", "Longitude", "Year"))


dfAgg
}


#wnvAugmented <- augmentTestData(wnv)

testAugmented <- augmentTestData(test)

table(is.na(testAugmented$pSpecies))

```
Two transformation function because otherwise we can rescore them in Kaggle

```{r}
saveRDS(wnvAgg , file = "wnvAgg.RDS")
saveRDS(testAugmented , file = "testAugmented.RDS")


```
